package br.aeroclube.pojo;
// Generated 11/07/2016 08:40:05 by Hibernate Tools 4.3.1


import br.aeroclube.hibernate.SampleEntity;
import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedores generated by hbm2java
 */
public class Fornecedores  implements java.io.Serializable, SampleEntity {


     private int idFornecedores;
     private String nomeFornecedor;
     private Set produtoses = new HashSet(0);

    public Fornecedores() {
    }

	
    public Fornecedores(int idFornecedores) {
        this.idFornecedores = idFornecedores;
    }
    public Fornecedores(int idFornecedores, String nomeFornecedor, Set produtoses) {
       this.idFornecedores = idFornecedores;
       this.nomeFornecedor = nomeFornecedor;
       this.produtoses = produtoses;
    }
   
    public int getIdFornecedores() {
        return this.idFornecedores;
    }
    
    public void setIdFornecedores(int idFornecedores) {
        this.idFornecedores = idFornecedores;
    }
    
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }
    public Set getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set produtoses) {
        this.produtoses = produtoses;
    }

    @Override
    public int getId() {
        return idFornecedores;
    }




}


