package br.aeroclube.pojo;
// Generated 11/07/2016 08:40:05 by Hibernate Tools 4.3.1

import br.aeroclube.hibernate.ProdutosHelper;




/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private int idProdutos;
     private Fornecedores fornecedores;
     private Categoria categoria;
     private String nomeProduto;
     private String precoProduto;
     int Fornecedores_idFornecedores;
     int Categoria_idCategoria;

    public Produtos() {
    }

	
    public Produtos(int idProdutos, Fornecedores fornecedores) {
        this.idProdutos = idProdutos;
        this.fornecedores = fornecedores;
    }
    public Produtos(int idProdutos, Fornecedores fornecedores, Categoria categoria, String nomeProduto, String precoProduto) {
       this.idProdutos = idProdutos;
       this.fornecedores = fornecedores;
       this.nomeProduto = nomeProduto;
       this.precoProduto = precoProduto;
       this.categoria = categoria;
    }

    public int getFornecedores_idFornecedores() {
        return Fornecedores_idFornecedores;
    }

    public void setFornecedores_idFornecedores(int Fornecedores_idFornecedores) {
        if(this.fornecedores==null) {
            this.fornecedores = new Fornecedores();
        }
        ProdutosHelper h = new ProdutosHelper();
        this.fornecedores = (Fornecedores) h.getFornecedores(Fornecedores_idFornecedores);
        this.Fornecedores_idFornecedores = Fornecedores_idFornecedores;
    }

    public int getCategoria_idCategoria() {
        return Categoria_idCategoria;
    }

    public void setCategoria_idCategoria(int Categoria_idCategoria) {
        if(this.categoria==null) {
            this.categoria = new Categoria();
        }
        ProdutosHelper h = new ProdutosHelper();
        this.categoria = (Categoria) h.getCategoria(Categoria_idCategoria);
        this.Categoria_idCategoria = Categoria_idCategoria;
    }

    public Categoria getCategoria() {
        return categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    
    public Integer getIdCategoria() {
        return this.categoria.getIdCategoria();
    }
      
    public void setIdCategoria(Integer idCategoria) {
        this.categoria.setIdCategoria(idCategoria);
    }
   
    public int getIdFornecedores() {
        return this.fornecedores.getIdFornecedores();
    }
    
    public void setIdFornecedores(int idFornecedores) {
        this.fornecedores.setIdFornecedores(idFornecedores);
    }
    
    
    public int getIdProdutos() {
        return this.idProdutos;
    }
    
    public void setIdProdutos(int idProdutos) {
        this.idProdutos = idProdutos;
    }
    public Fornecedores getFornecedores() {
        return this.fornecedores;
    }
    
    public void setFornecedores(Fornecedores fornecedores) {
        if(this.fornecedores == null)
            this.fornecedores = new Fornecedores();
        this.fornecedores = fornecedores;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public String getPrecoProduto() {
        return this.precoProduto;
    }
    
    public void setPrecoProduto(String precoProduto) {
        this.precoProduto = precoProduto;
    }




}


